apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example-voting-app.fullname" . }}-redis
  labels:
    app: {{ template "example-voting-app.fullname" . }}-redis
    {{- include "example-voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "example-voting-app.fullname" . }}-redis
      {{- include "example-voting-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "example-voting-app.fullname" . }}-redis
        {{- include "example-voting-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "example-voting-app.serviceAccountName.redis" . }}-redis
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
      - name: redis-data
        emptyDir: {} 
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
