apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-voting-app.fullname" . }}-vote
  labels:
    app: {{ template "example-voting-app.fullname" . }}-vote
    {{- include "example-voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "example-voting-app.fullname" . }}-vote
      {{- include "example-voting-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.vote.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "example-voting-app.fullname" . }}-vote
        {{- include "example-voting-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "example-voting-app.serviceAccountName.vote" . }}-vote
      securityContext:
        {{- toYaml .Values.vote.podSecurityContext | nindent 8 }}
      containers:
        - name: vote
          securityContext:
            {{- toYaml .Values.vote.securityContext | nindent 12 }}
          image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vote.image.pullPolicy }}
          {{- with .Values.vote.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: prometheus
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.vote.resources | nindent 12 }}
      {{- with .Values.vote.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vote.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vote.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
