apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-voting-app.fullname" . }}-vote
  labels:
    app: {{ template "example-voting-app.fullname" . }}-vote
    {{- include "example-voting-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    app: {{ template "example-voting-app.fullname" . }}-vote
    {{- include "example-voting-app.selectorLabels" . | nindent 4 }}
